// Shared error type across AR-002's deployment pipeline modules
// (manifest, binding, release, staging, production) — one error surface,
// same idiom as AppRegistryError/DeploymentAuthorizationError.
export class DeploymentPipelineError extends Error {
  // Optional diagnostic-only detail (e.g. the provider's own error text) --
  // same "admin-facing, not a new contract field" precedent as
  // validation_summary_json.providerErrorDetail on the staging path.
  constructor(public readonly code: string, public readonly detail?: string) {
    super(code);
    this.name = "DeploymentPipelineError";
  }
}

const STATUS_BY_CODE: Record<string, number> = {
  APP_NOT_ACTIVE: 409,
  APP_MANIFEST_INVALID: 422,
  APP_IDENTITY_MISMATCH: 422,
  APP_MANIFEST_PATH_INVALID: 422,
  DEPLOYMENT_PROVIDER_UNSUPPORTED: 422,
  DEPLOYMENT_PROVIDER_UNAVAILABLE: 502,
  DEPLOYMENT_PROJECT_NOT_VERIFIED: 422,
  DEPLOYMENT_REPOSITORY_MISMATCH: 422,
  DEPLOYMENT_PROJECT_ALREADY_BOUND: 409,
  DEPLOYMENT_DOMAIN_NOT_APPROVED: 422,
  DEPLOYMENT_BINDING_NOT_FOUND: 404,
  DEPLOYMENT_VERSION_CONFLICT: 409,
  IDEMPOTENCY_KEY_REUSED: 409,
  MUTATION_IN_PROGRESS: 409,
  RELEASE_BUILD_FAILED: 422,
  RELEASE_GATE_FAILED: 422,
  RELEASE_NOT_FOUND: 404,
  RELEASE_NOT_VERIFIED: 409,
  RELEASE_ARTIFACT_CHANGED: 409,
  STAGING_VALIDATION_FAILED: 422,
  FORBIDDEN: 403,
  REAUTHENTICATION_REQUIRED: 401,
  RECENT_REAUTHENTICATION_REQUIRED: 401,
  DEPLOYMENT_PIPELINE_DISABLED: 409,
  DEPLOYMENT_PROMOTION_IN_PROGRESS: 409,
  DEPLOYMENT_ORIGIN_REJECTED: 422,
  PRODUCTION_VALIDATION_FAILED: 422,
  DEPLOYMENT_ACTIVE_SESSIONS: 409,
  INVALID_REQUEST: 400,
  INVALID_BODY: 400,
  // AR-002 session 2
  DEPLOYMENT_WINDOW_LEAD_TIME_REQUIRED: 422,
  DEPLOYMENT_WINDOW_CONFLICT: 409,
  DEPLOYMENT_WINDOW_NOT_FOUND: 404,
  DEPLOYMENT_WINDOW_NOT_READY: 409,
  DEPLOYMENT_SESSIONS_ACTIVE: 409,
  ROLLBACK_TARGET_NOT_AVAILABLE: 409,
  ROLLBACK_FAILED: 502,
  RELEASE_BACKWARD_COMPATIBILITY_FAILED: 422,
  WEBHOOK_SIGNATURE_INVALID: 401,
  WEBHOOK_REPLAYED: 409,
};

export function deploymentPipelineErrorStatus(code: string): number {
  return STATUS_BY_CODE[code] ?? 400;
}
