export const PUBLIC_API_ROUTE = "public" as const;

type RouteRule = { pattern: RegExp; methods: Readonly<Record<string, string | typeof PUBLIC_API_ROUTE>> };

export const API_ROUTE_AUTHORIZATION: readonly RouteRule[] = [
  { pattern: /^\/v1\/apps$/, methods: { GET: PUBLIC_API_ROUTE } },
  { pattern: /^\/v1\/apps\/[^/]+$/, methods: { GET: PUBLIC_API_ROUTE } },
  { pattern: /^\/v1\/account\/email-change\/cancel$/, methods: { POST: "parent.account.email_change.cancel" } },
  { pattern: /^\/v1\/account\/email-change\/request$/, methods: { POST: "parent.account.email_change.request" } },
  { pattern: /^\/v1\/account\/email-change\/resend$/, methods: { POST: "parent.account.email_change.resend" } },
  { pattern: /^\/v1\/account\/password\/change$/, methods: { POST: "parent.account.password.change" } },
  { pattern: /^\/v1\/account\/security$/, methods: { GET: "parent.account.security.read" } },
  { pattern: /^\/v1\/account\/soft-delete$/, methods: { POST: "parent.account.delete" } },
  { pattern: /^\/v1\/parent\/profile$/, methods: { GET: "parent.profile.read", PATCH: "parent.profile.update" } },
  { pattern: /^\/v1\/parent\/consent\/processing-envelope$/,
    methods: { GET: "parent.consent.processing_envelope.read", POST: "parent.consent.processing_envelope.update" } },
  { pattern: /^\/v1\/parent\/notification-preferences$/, methods: { GET: "parent.notification_preferences.read", PATCH: "parent.notification_preferences.update" } },
  { pattern: /^\/v1\/billing\/checkout-intents$/, methods: { POST: "parent.billing.checkout.create" } },
  { pattern: /^\/v1\/parent\/subscriptions$/, methods: { GET: "parent.billing.subscriptions.read" } },
  { pattern: /^\/v1\/parent\/subscriptions\/[^/]+\/billing-status$/, methods: { GET: "parent.billing.status.read" } },
  { pattern: /^\/v1\/parent\/subscriptions\/[^/]+\/disable-auto-renew$/, methods: { POST: "parent.billing.auto_renew.disable" } },
  { pattern: /^\/v1\/parent\/subscriptions\/[^/]+\/cancel$/, methods: { POST: "parent.billing.subscription.cancel" } },
  { pattern: /^\/v1\/parent\/subscriptions\/[^/]+\/resume-auto-renew$/, methods: { POST: "parent.billing.auto_renew.resume" } },
  { pattern: /^\/v1\/parent\/subscriptions\/[^/]+\/payment-recovery-status$/, methods: { GET: "parent.billing.payment_recovery.read" } },
  { pattern: /^\/v1\/parent\/subscriptions\/[^/]+\/payment-method-update-session$/, methods: { POST: "parent.billing.payment_method.update" } },
  { pattern: /^\/v1\/webhooks\/payments\/[^/]+$/, methods: { POST: "service.billing.provider_event" } },
  { pattern: /^\/v1\/subscription-reassignment-cases$/, methods: { POST: "parent.billing.reassignment_case.create" } },
  { pattern: /^\/v1\/onboarding\/ensure-parent-profile$/, methods: { POST: "parent.onboarding.ensure" } },
  { pattern: /^\/v1\/learner-selection$/, methods: { GET: "parent.learners.list", PUT: "parent.learner.select" } },
  { pattern: /^\/v1\/learner-home$/, methods: { GET: "learner.home.read" } },
  { pattern: /^\/v1\/learner-achievements$/, methods: { GET: "learner.achievements.read" } },
  { pattern: /^\/v1\/learner-apps\/[^/]+\/journey$/, methods: { GET: "learner.journey.read" } },
  { pattern: /^\/v1\/learner-consistency$/, methods: { GET: "learner.consistency.read" } },
  { pattern: /^\/v1\/learner-mode\/exit$/, methods: { POST: "learner.mode.exit" } },
  { pattern: /^\/v1\/learner-mode\/enter\/options$/, methods: { POST: "learner.mode.enter" } },
  { pattern: /^\/v1\/learner-mode\/enter\/verify$/, methods: { POST: "learner.mode.enter" } },
  { pattern: /^\/v1\/learners$/, methods: { POST: "parent.learner.manage" } },
  { pattern: /^\/v1\/learners\/[^/]+$/, methods: { GET: "parent.learner.read", PATCH: "parent.learner.manage" } },
  { pattern: /^\/v1\/learners\/[^/]+\/session-credits$/, methods: { GET: "parent.learner.credits.read" } },
  { pattern: /^\/v1\/learners\/[^/]+\/reset-weekly-limit$/, methods: { POST: "parent.learner.manage" } },
  { pattern: /^\/v1\/learners\/[^/]+\/progress$/, methods: { GET: "parent.learner.report.read" } },
  { pattern: /^\/v1\/parent\/learners\/[^/]+\/past-apps$/, methods: { GET: "parent.learner.past_apps.read" } },
  { pattern: /^\/v1\/parent\/learners\/[^/]+\/achievements$/, methods: { GET: "parent.learner.achievements.read" } },
  { pattern: /^\/v1\/parent\/learners\/[^/]+\/apps\/[^/]+\/journey$/, methods: { GET: "parent.learner.journey.read" } },
  { pattern: /^\/v1\/parent\/learners\/[^/]+\/consistency$/, methods: { GET: "parent.learner.consistency.read" } },
  { pattern: /^\/v1\/parent\/learners\/[^/]+\/past-apps\/[^/]+\/subscribe-again$/, methods: { POST: "parent.learner.subscribe_again.create" } },
  { pattern: /^\/v1\/learners\/[^/]+\/passkeys$/, methods: { GET: "parent.passkeys.manage" } },
  { pattern: /^\/v1\/learners\/[^/]+\/passkeys\/registration-options$/, methods: { POST: "parent.passkeys.manage" } },
  { pattern: /^\/v1\/learners\/[^/]+\/passkeys\/registration-verify$/, methods: { POST: "parent.passkeys.manage" } },
  { pattern: /^\/v1\/learners\/[^/]+\/passkeys\/[^/]+\/revoke$/, methods: { POST: "parent.passkeys.manage" } },
  { pattern: /^\/v1\/parent\/attention$/, methods: { GET: "parent.attention.read" } },
  { pattern: /^\/v1\/parent\/attention\/summary$/, methods: { GET: "parent.attention.summary.read" } },
  // API-PD-004/API-PD-005 (PD3-G01/G02): the frozen attention-center/
  // attention-summary paths. The /v1/parent/attention[/summary] routes
  // above remain as internal/compat endpoints, not the frozen contract.
  { pattern: /^\/v1\/parent\/attention-center$/, methods: { GET: "parent.attention.read" } },
  { pattern: /^\/v1\/parent\/attention-summary$/, methods: { GET: "parent.attention.summary.read" } },
  { pattern: /^\/v1\/parent\/dashboard$/, methods: { GET: "parent.dashboard.read" } },
  { pattern: /^\/v1\/parent\/learners\/[^/]+$/, methods: { GET: "parent.learner.detail.read" } },
  // API-PD-002/API-PD-003 (PD2-G01/G02): the frozen learner-detail and
  // compact app-selector routes. /apps/{appId} below remains as an
  // internal/compat single-app detail lookup, not the frozen selector API.
  { pattern: /^\/v1\/parent\/learners\/[^/]+\/detail$/, methods: { GET: "parent.learner.detail.read" } },
  { pattern: /^\/v1\/parent\/learners\/[^/]+\/apps$/, methods: { GET: "parent.learner.detail.read" } },
  { pattern: /^\/v1\/parent\/learners\/[^/]+\/apps\/[^/]+$/, methods: { GET: "parent.learner.app_detail.read" } },
  { pattern: /^\/v1\/parent\/shell-context$/, methods: { GET: "parent.shell_context.read" } },
  // API-NT-006: 13-month parent transactional-communication history.
  { pattern: /^\/v1\/parent\/communication-history$/, methods: { GET: "parent.notification_history.read" } },
  { pattern: /^\/v1\/learner-sessions$/, methods: { POST: "learner.session.start" } },
  { pattern: /^\/v1\/learner-sessions\/[^/]+\/launch-dispatch$/, methods: { POST: "learner.session.start" } },
  { pattern: /^\/v1\/learner-sessions\/[^/]+\/technical-credit$/, methods: { POST: "learner.technical_issue.confirm" } },
  { pattern: /^\/v1\/learner-sessions\/[^/]+\/cancel-start$/, methods: { POST: "learner.session.cancel_start" } },
  { pattern: /^\/v1\/admin\/accounts\/[^/]+\/restore$/, methods: { POST: "admin.account.restore" } },
  { pattern: /^\/v1\/admin\/staff\/invitations$/, methods: { POST: "admin.staff.invitation.create" } },
  { pattern: /^\/v1\/admin\/session-context$/, methods: { GET: "admin.staff.session_context.read" } },
  { pattern: /^\/v1\/admin\/auth\/login$/, methods: { POST: PUBLIC_API_ROUTE } },
  { pattern: /^\/v1\/admin\/auth\/reauth$/, methods: { POST: "admin.staff.passkey.assertion_options" } },
  { pattern: /^\/v1\/admin\/auth\/passkey\/registration-options$/, methods: { POST: "admin.staff.passkey.registration_options" } },
  { pattern: /^\/v1\/admin\/auth\/passkey\/register$/, methods: { POST: "admin.staff.passkey.register" } },
  { pattern: /^\/v1\/admin\/auth\/passkey\/assertion-options$/, methods: { POST: "admin.staff.passkey.assertion_options" } },
  { pattern: /^\/v1\/admin\/auth\/passkey\/verify$/, methods: { POST: "admin.staff.passkey.verify" } },
  { pattern: /^\/v1\/admin\/staff\/[^/]+\/status$/, methods: { PATCH: "admin.staff.status.update" } },
  { pattern: /^\/v1\/admin\/staff\/[^/]+\/roles$/, methods: { PUT: "admin.staff.roles.update" } },
  { pattern: /^\/v1\/admin\/staff$/, methods: { GET: "admin.staff.list.read" } },
  { pattern: /^\/v1\/admin\/billing\/refund-cases$/, methods: { POST: "admin.billing.refund.create" } },
  { pattern: /^\/v1\/admin\/billing\/refund-cases\/[^/]+\/confirm$/, methods: { POST: "admin.billing.refund.confirm" } },
  { pattern: /^\/v1\/admin\/subscription-reassignment-cases\/[^/]+$/, methods: { GET: "admin.billing.reassignment_case.read" } },
  { pattern: /^\/v1\/admin\/subscriptions\/[^/]+\/reassign-learner$/, methods: { POST: "admin.billing.subscription.reassign" } },
  { pattern: /^\/v1\/admin\/analytics\/daily$/, methods: { GET: "admin.analytics.daily.read" } },
  { pattern: /^\/v1\/admin\/analytics\/daily\/export$/, methods: { GET: "admin.analytics.daily.export" } },
  { pattern: /^\/v1\/admin\/analytics\/runs$/, methods: { GET: "admin.analytics.runs.read" } },
  { pattern: /^\/v1\/admin\/analytics\/runs\/[^/]+\/retry$/, methods: { POST: "admin.analytics.run.retry" } },
  { pattern: /^\/v1\/admin\/learners$/, methods: { GET: "admin.learner.list" } },
  { pattern: /^\/v1\/admin\/learners\/[^/]+\/session-limit$/, methods: { PATCH: "admin.learner.session_limit.update" } },
  { pattern: /^\/v1\/admin\/apps$/, methods: { GET: "admin.app.list", POST: "admin.app.create" } },
  { pattern: /^\/v1\/admin\/apps\/bootstrap$/, methods: { POST: "admin.app.bootstrap" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+$/, methods: { GET: "admin.app.read", PATCH: "admin.app.update" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/activate$/, methods: { POST: "admin.app.activate" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/restore$/, methods: { POST: "admin.app.restore" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/soft-delete$/, methods: { POST: "admin.app.delete" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployment-bindings$/, methods: { GET: "admin.deployment.bindings.read", POST: "admin.deployment.bindings.create" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployment-bindings\/[^/]+$/, methods: { PATCH: "admin.deployment.bindings.update" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployment-bindings\/[^/]+\/verify$/, methods: { POST: "admin.deployment.bindings.verify" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/releases$/, methods: { GET: "admin.deployment.releases.read" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/releases\/[^/]+\/deploy-staging$/, methods: { POST: "admin.deployment.release.deploy_staging" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/releases\/[^/]+\/approve-production$/, methods: { POST: "admin.deployment.release.approve_production" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployments$/, methods: { GET: "admin.deployment.deployments.read" } },
  { pattern: /^\/v1\/internal\/apps\/[^/]+\/releases$/, methods: { POST: "service.deployment.release_create" } },
  { pattern: /^\/v1\/internal\/apps\/[^/]+\/published-deployment$/, methods: { GET: "service.deployment.published.read" } },
  { pattern: /^\/v1\/internal\/apps\/[^/]+\/achievement-contract$/, methods: { GET: "app.achievement.contract.read" } },
  { pattern: /^\/v1\/internal\/apps\/[^/]+\/availability$/, methods: { GET: "service.app_availability.read" } },
  { pattern: /^\/v1\/internal\/deployments\/safety-sweep$/, methods: { POST: "service.deployment.safety_sweep" } },
  { pattern: /^\/v1\/internal\/deployments\/window-sweep$/, methods: { POST: "service.deployment.window_sweep" } },
  { pattern: /^\/v1\/internal\/deployment-provider\/webhook$/, methods: { POST: "service.deployment.webhook_ingest" } },
  { pattern: /^\/v1\/internal\/deployments\/retention-purge$/, methods: { POST: "service.deployment.retention_purge" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployments\/[^/]+\/schedule$/, methods: { POST: "deployment.schedule" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployments\/[^/]+\/reschedule$/, methods: { POST: "deployment.reschedule" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployments\/[^/]+\/cancel$/, methods: { POST: "deployment.cancel" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployments\/[^/]+\/promote$/, methods: { POST: "deployment.promote" } },
  // AR-002 session 2: this URL is now backed by the real rollback service
  // (src/lib/deployment-rollback/service.ts), not AU-001's
  // deployment-service.ts scaffold — deployment.rollback (AU-001's own
  // action, still defined in AUTHORIZATION_ACTIONS for
  // tests/au-001.acceptance.test.ts AC44) is intentionally no longer the
  // declaration for this path.
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployments\/[^/]+\/rollback$/, methods: { POST: "admin.deployment.rollback" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployment-windows$/, methods: { GET: "admin.deployment.windows.read", POST: "admin.deployment.windows.schedule" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployment-windows\/[^/]+$/, methods: { PATCH: "admin.deployment.windows.reschedule" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployment-windows\/[^/]+\/cancel$/, methods: { POST: "admin.deployment.windows.cancel" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/availability$/, methods: { GET: "admin.app_availability.read" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/maintenance-windows$/, methods: { POST: "admin.app_availability.manage" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/maintenance-windows\/[^/]+$/, methods: { PATCH: "admin.app_availability.manage" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/availability-transition$/, methods: { POST: "admin.app_availability.manage" } },
  { pattern: /^\/v1\/internal\/analytics\/daily-contribution$/, methods: { POST: "service.analytics.contribute" } },
  { pattern: /^\/v1\/internal\/analytics\/daily-runs\/[^/]+$/, methods: { POST: "service.analytics.run" } },
  { pattern: /^\/v1\/internal\/authorization\/decision$/, methods: { POST: "service.authorization.decide" } },
  { pattern: /^\/v1\/internal\/entitlements\/apply-paid-cycle$/, methods: { POST: "service.entitlements.apply_cycle" } },
  { pattern: /^\/v1\/internal\/entitlements\/evaluate-access$/, methods: { POST: "service.entitlements.evaluate_access" } },
  { pattern: /^\/v1\/internal\/billing\/reconcile$/, methods: { POST: "service.billing.reconcile" } },
  { pattern: /^\/v1\/internal\/billing\/upcoming-renewal-reminder-sweep$/, methods: { POST: "service.billing.renewal_reminder" } },
  { pattern: /^\/v1\/internal\/billing\/grace-expiry-sweep$/, methods: { POST: "service.billing.grace_expiry" } },
  { pattern: /^\/v1\/internal\/app-launch\/exchange$/, methods: { POST: "app.launch.exchange" } },
  { pattern: /^\/v1\/internal\/app-session-grants\/[^/]+\/renew$/, methods: { POST: "app.grant.renew" } },
  { pattern: /^\/v1\/internal\/app-session-grants\/[^/]+\/status$/, methods: { GET: "app.grant.status" } },
  { pattern: /^\/v1\/internal\/learner-achievements$/, methods: { POST: "app.achievement.write" } },
  { pattern: /^\/v1\/internal\/learner-achievements\/[^/]+\/revoke$/, methods: { POST: "app.achievement.revoke" } },
  { pattern: /^\/v1\/internal\/learner-journey\/milestones$/, methods: { POST: "app.journey.milestone.write" } },
  { pattern: /^\/v1\/internal\/learner-journey\/retention-reconcile$/, methods: { POST: "service.journey.retention" } },
  { pattern: /^\/v1\/internal\/learning-reminders\/evaluate$/, methods: { POST: "service.learning_reminders.evaluate" } },
  { pattern: /^\/v1\/internal\/learning-reminders\/send$/, methods: { POST: "service.learning_reminders.send" } },
  { pattern: /^\/v1\/internal\/learning-reminders\/reconcile-delivery$/, methods: { POST: "service.learning_reminders.reconcile" } },
  { pattern: /^\/v1\/internal\/learner-consistency\/standard-session-committed$/, methods: { POST: "service.consistency.contribute" } },
  { pattern: /^\/v1\/internal\/learner-consistency\/finalize-week$/, methods: { POST: "service.consistency.finalize" } },
  { pattern: /^\/v1\/internal\/learner-consistency\/reconcile$/, methods: { POST: "service.consistency.reconcile" } },
  { pattern: /^\/v1\/internal\/learner-consistency\/[^/]+\/cadence-completion-context$/, methods: { GET: "service.consistency.context.read" } },
  { pattern: /^\/v1\/internal\/learner-app-progress\/completions$/, methods: { GET: "app.progress.completions.read" } },
  { pattern: /^\/v1\/internal\/learner-app-progress\/current$/, methods: { GET: "app.progress.current.read", PUT: "app.progress.write" } },
  { pattern: /^\/v1\/internal\/learner-app-progress\/summary$/, methods: { PUT: "app.progress.summary.write" } },
  { pattern: /^\/v1\/internal\/learner-app-progress\/lessons\/[^/]+\/complete$/, methods: { POST: "app.lesson.complete" } },
  { pattern: /^\/v1\/internal\/learner-sessions\/[^/]+\/complete$/, methods: { POST: "app.session.complete" } },
  { pattern: /^\/v1\/internal\/learner-sessions\/[^/]+\/disconnect$/, methods: { POST: "app.session.disconnect" } },
  { pattern: /^\/v1\/internal\/learner-sessions\/[^/]+\/exit-state$/, methods: { GET: "app.session.exit_state.read" } },
  { pattern: /^\/v1\/internal\/learner-sessions\/[^/]+\/finish$/, methods: { POST: "app.session.finish" } },
  { pattern: /^\/v1\/internal\/learner-sessions\/[^/]+\/mark-resumable$/, methods: { POST: "app.session.mark_resumable" } },
  { pattern: /^\/v1\/internal\/learner-sessions\/[^/]+\/resume$/, methods: { POST: "app.session.resume" } },
  { pattern: /^\/v1\/internal\/learner-sessions\/[^/]+\/usable-launch$/, methods: { POST: "app.session.usable_launch" } },
  { pattern: /^\/v1\/internal\/learner-app-progress\/validate-integrity$/, methods: { POST: "app.progress.integrity.validate" } },
  { pattern: /^\/v1\/internal\/learner-app-progress\/reconcile-integrity$/, methods: { POST: "service.progress_integrity.reconcile" } },
  { pattern: /^\/v1\/admin\/progress-integrity-incidents\/[^/]+$/, methods: { GET: "admin.progress_integrity.incident.read" } },
  { pattern: /^\/v1\/admin\/progress-integrity-incidents\/[^/]+\/action$/, methods: { POST: "admin.progress_integrity.incident.action" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/progress-integrity-health$/, methods: { GET: "admin.progress_integrity.health.read" } },
  { pattern: /^\/v1\/internal\/learner-app-progress\/recover-current$/, methods: { POST: "app.progress.recover" } },
  { pattern: /^\/v1\/internal\/learner-app-progress\/reconcile-recovery$/, methods: { POST: "service.progress_recovery.reconcile" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/progress-recovery-incidents$/, methods: { GET: "admin.progress_recovery.incidents.read" } },
  { pattern: /^\/v1\/internal\/entitlements\/apply-lifecycle-event$/, methods: { POST: "service.entitlements.apply_lifecycle_event" } },
  { pattern: /^\/v1\/internal\/entitlements\/process-due-transitions$/, methods: { POST: "service.entitlements.process_due_transitions" } },
  { pattern: /^\/v1\/internal\/entitlements\/reconcile-lifecycle$/, methods: { POST: "service.entitlements.reconcile_lifecycle" } },
  { pattern: /^\/v1\/admin\/entitlements\/[^/]+\/revoke$/, methods: { POST: "admin.entitlements.security_revoke" } },
  { pattern: /^\/v1\/internal\/entitlements\/reconcile-integrity$/, methods: { POST: "service.entitlements.reconcile_integrity" } },
  { pattern: /^\/v1\/internal\/entitlements\/reconcile-paid-cycle\/[^/]+$/, methods: { POST: "service.entitlements.reconcile_paid_cycle" } },
  { pattern: /^\/v1\/internal\/entitlements\/reconcile-learner-app$/, methods: { POST: "service.entitlements.reconcile_learner_app" } },
  { pattern: /^\/v1\/internal\/learner-launcher\/invalidate$/, methods: { POST: "service.launcher.invalidate" } },
  { pattern: /^\/v1\/internal\/learner-launcher\/reconcile-freshness$/, methods: { POST: "service.launcher.reconcile_freshness" } },
  { pattern: /^\/v1\/admin\/entitlement-integrity-incidents\/[^/]+$/, methods: { GET: "admin.entitlement_integrity.incident.read" } },
  { pattern: /^\/v1\/admin\/entitlement-integrity-incidents\/[^/]+\/action$/, methods: { POST: "admin.entitlement_integrity.incident.action" } },
  { pattern: /^\/v1\/webhooks\/financial-events$/, methods: { POST: "service.billing.financial_event_webhook" } },
  { pattern: /^\/v1\/internal\/notifications\/transactional-intents$/, methods: { POST: "service.notifications.enqueue" } },
  { pattern: /^\/v1\/internal\/notifications\/delivery-run$/, methods: { POST: "service.notifications.deliver" } },
  { pattern: /^\/v1\/internal\/notifications\/provider-events$/, methods: { POST: "service.notifications.provider_event" } },
  { pattern: /^\/v1\/internal\/notifications\/reconcile$/, methods: { POST: "service.notifications.reconcile" } },
  { pattern: /^\/v1\/internal\/notifications\/by-source\/[^/]+\/[^/]+$/, methods: { GET: "service.notifications.read" } },
  { pattern: /^\/v1\/internal\/notifications\/health\/monitor$/, methods: { POST: "service.notifications.monitor_health" } },
  { pattern: /^\/v1\/admin\/support\/resolve-customer$/, methods: { POST: "admin.support.resolve_customer" } },
  { pattern: /^\/v1\/admin\/support\/cases$/, methods: { POST: "admin.support.case.create", GET: "admin.support.case.list" } },
  { pattern: /^\/v1\/admin\/support\/cases\/[^/]+$/, methods: { GET: "admin.support.case.read", PATCH: "admin.support.case.workflow_update" } },
  { pattern: /^\/v1\/admin\/support\/cases\/[^/]+\/notes$/, methods: { POST: "admin.support.case.note.add" } },
  { pattern: /^\/v1\/admin\/support\/cases\/[^/]+\/reopen$/, methods: { POST: "admin.support.case.reopen" } },
  { pattern: /^\/v1\/admin\/support\/cases\/[^/]+\/billing$/, methods: { GET: "admin.support.billing.workspace.read" } },
  { pattern: /^\/v1\/admin\/support\/cases\/[^/]+\/billing\/reassignment-eligibility$/, methods: { GET: "admin.support.billing.reassignment_eligibility.read" } },
  { pattern: /^\/v1\/admin\/support\/cases\/[^/]+\/billing\/reassign-subscription$/, methods: { POST: "admin.support.billing.reassign" } },
  { pattern: /^\/v1\/admin\/support\/cases\/[^/]+\/billing\/refund-eligibility$/, methods: { GET: "admin.support.billing.refund_eligibility.read" } },
  { pattern: /^\/v1\/admin\/support\/cases\/[^/]+\/billing\/refunds$/, methods: { POST: "admin.support.billing.refund" } },
  { pattern: /^\/v1\/admin\/operations\/changes$/, methods: { POST: "admin.operations.change.create", GET: "admin.operations.change.list" } },
  { pattern: /^\/v1\/admin\/operations\/changes\/[^/]+$/, methods: { GET: "admin.operations.change.read", PATCH: "admin.operations.change.workflow_update" } },
  { pattern: /^\/v1\/admin\/platform\/governance$/, methods: { GET: "admin.platform.governance.read" } },
  { pattern: /^\/v1\/admin\/platform\/staff\/[^/]+\/recovery-sessions$/, methods: { POST: "admin.staff.recovery_session.create" } },
  // Pre-MFA, self-service by the target staff member — no admin session
  // exists yet at this point in either flow (rules 50, 59-60, API-AD-028).
  { pattern: /^\/v1\/admin\/platform\/recovery\/break-glass$/, methods: { POST: PUBLIC_API_ROUTE } },
  { pattern: /^\/v1\/admin\/platform\/recovery\/consume$/, methods: { POST: PUBLIC_API_ROUTE } },
  { pattern: /^\/v1\/admin\/platform\/recovery-codes\/rotate$/, methods: { POST: "admin.platform.recovery_codes.rotate" } },
  { pattern: /^\/v1\/admin\/platform\/audit$/, methods: { GET: "admin.platform.audit.read" } },
  { pattern: /^\/v1\/admin\/monitoring\/status$/, methods: { GET: "admin.monitoring.status.read" } },
  { pattern: /^\/v1\/admin\/monitoring\/alerts$/, methods: { GET: "admin.monitoring.alerts.read" } },
  { pattern: /^\/v1\/internal\/monitoring\/sync$/, methods: { POST: "service.monitoring.sync" } },
  { pattern: /^\/v1\/internal\/backup-status$/, methods: { POST: "service.backup.report_status" } },
  { pattern: /^\/v1\/admin\/platform\/parent-restorations$/, methods: { POST: "admin.account.restore" } },
  { pattern: /^\/v1\/admin\/platform\/recovery-tests$/, methods: {
    GET: "admin.platform.recovery_test.read", POST: "admin.platform.recovery_test.start" } },
  { pattern: /^\/v1\/admin\/platform\/recovery-tests\/[^/]+$/, methods: {
    GET: "admin.platform.recovery_test.read", PATCH: "admin.platform.recovery_test.update" } },
] as const;

export function resolveApiRouteAuthorization(method: string, pathname: string) {
  const route = API_ROUTE_AUTHORIZATION.find((candidate) => candidate.pattern.test(pathname));
  return route?.methods[method.toUpperCase()];
}
