export const PUBLIC_API_ROUTE = "public" as const;

type RouteRule = { pattern: RegExp; methods: Readonly<Record<string, string | typeof PUBLIC_API_ROUTE>> };

export const API_ROUTE_AUTHORIZATION: readonly RouteRule[] = [
  { pattern: /^\/v1\/apps$/, methods: { GET: PUBLIC_API_ROUTE } },
  { pattern: /^\/v1\/apps\/[^/]+$/, methods: { GET: PUBLIC_API_ROUTE } },
  { pattern: /^\/v1\/account\/email-change\/cancel$/, methods: { POST: "parent.account.email_change.cancel" } },
  { pattern: /^\/v1\/account\/email-change\/request$/, methods: { POST: "parent.account.email_change.request" } },
  { pattern: /^\/v1\/account\/email-change\/resend$/, methods: { POST: "parent.account.email_change.resend" } },
  { pattern: /^\/v1\/account\/password\/change$/, methods: { POST: "parent.account.password.change" } },
  { pattern: /^\/v1\/account\/security$/, methods: { GET: "parent.account.security.read" } },
  { pattern: /^\/v1\/account\/soft-delete$/, methods: { POST: "parent.account.delete" } },
  { pattern: /^\/v1\/parent\/profile$/, methods: { GET: "parent.profile.read", PATCH: "parent.profile.update" } },
  { pattern: /^\/v1\/billing\/checkout-intents$/, methods: { POST: "parent.billing.checkout.create" } },
  { pattern: /^\/v1\/parent\/subscriptions$/, methods: { GET: "parent.billing.subscriptions.read" } },
  { pattern: /^\/v1\/parent\/subscriptions\/[^/]+\/billing-status$/, methods: { GET: "parent.billing.status.read" } },
  { pattern: /^\/v1\/parent\/subscriptions\/[^/]+\/disable-auto-renew$/, methods: { POST: "parent.billing.auto_renew.disable" } },
  { pattern: /^\/v1\/parent\/subscriptions\/[^/]+\/cancel$/, methods: { POST: "parent.billing.subscription.cancel" } },
  { pattern: /^\/v1\/parent\/subscriptions\/[^/]+\/resume-auto-renew$/, methods: { POST: "parent.billing.auto_renew.resume" } },
  { pattern: /^\/v1\/parent\/subscriptions\/[^/]+\/payment-recovery-status$/, methods: { GET: "parent.billing.payment_recovery.read" } },
  { pattern: /^\/v1\/parent\/subscriptions\/[^/]+\/payment-method-update-session$/, methods: { POST: "parent.billing.payment_method.update" } },
  { pattern: /^\/v1\/webhooks\/payments\/[^/]+$/, methods: { POST: "service.billing.provider_event" } },
  { pattern: /^\/v1\/subscription-reassignment-cases$/, methods: { POST: "parent.billing.reassignment_case.create" } },
  { pattern: /^\/v1\/onboarding\/ensure-parent-profile$/, methods: { POST: "parent.onboarding.ensure" } },
  { pattern: /^\/v1\/learner-selection$/, methods: { GET: "parent.learners.list", PUT: "parent.learner.select" } },
  { pattern: /^\/v1\/learner-mode\/exit$/, methods: { POST: "learner.mode.exit" } },
  { pattern: /^\/v1\/learner-mode\/enter\/options$/, methods: { POST: "learner.mode.enter" } },
  { pattern: /^\/v1\/learner-mode\/enter\/verify$/, methods: { POST: "learner.mode.enter" } },
  { pattern: /^\/v1\/learners\/[^/]+$/, methods: { GET: "parent.learner.read", PATCH: "parent.learner.manage" } },
  { pattern: /^\/v1\/learners\/[^/]+\/session-credits$/, methods: { GET: "parent.learner.credits.read" } },
  { pattern: /^\/v1\/learners\/[^/]+\/progress$/, methods: { GET: "parent.learner.report.read" } },
  { pattern: /^\/v1\/learners\/[^/]+\/passkeys$/, methods: { GET: "parent.passkeys.manage" } },
  { pattern: /^\/v1\/learners\/[^/]+\/passkeys\/registration-options$/, methods: { POST: "parent.passkeys.manage" } },
  { pattern: /^\/v1\/learners\/[^/]+\/passkeys\/registration-verify$/, methods: { POST: "parent.passkeys.manage" } },
  { pattern: /^\/v1\/learners\/[^/]+\/passkeys\/[^/]+\/revoke$/, methods: { POST: "parent.passkeys.manage" } },
  { pattern: /^\/v1\/learner-sessions\/[^/]+\/launch-dispatch$/, methods: { POST: "learner.session.start" } },
  { pattern: /^\/v1\/learner-sessions\/[^/]+\/technical-credit$/, methods: { POST: "learner.technical_issue.confirm" } },
  { pattern: /^\/v1\/learner-sessions\/[^/]+\/cancel-start$/, methods: { POST: "learner.session.cancel_start" } },
  { pattern: /^\/v1\/admin\/accounts\/[^/]+\/restore$/, methods: { POST: "admin.account.restore" } },
  { pattern: /^\/v1\/admin\/subscription-reassignment-cases\/[^/]+$/, methods: { GET: "admin.billing.reassignment_case.read" } },
  { pattern: /^\/v1\/admin\/subscriptions\/[^/]+\/reassign-learner$/, methods: { POST: "admin.billing.subscription.reassign" } },
  { pattern: /^\/v1\/admin\/analytics\/daily$/, methods: { GET: "admin.analytics.daily.read" } },
  { pattern: /^\/v1\/admin\/analytics\/runs$/, methods: { GET: "admin.analytics.runs.read" } },
  { pattern: /^\/v1\/admin\/analytics\/runs\/[^/]+\/retry$/, methods: { POST: "admin.analytics.run.retry" } },
  { pattern: /^\/v1\/admin\/apps$/, methods: { GET: "admin.app.list", POST: "admin.app.create" } },
  { pattern: /^\/v1\/admin\/apps\/bootstrap$/, methods: { POST: "admin.app.bootstrap" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+$/, methods: { GET: "admin.app.read", PATCH: "admin.app.update" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/activate$/, methods: { POST: "admin.app.activate" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/restore$/, methods: { POST: "admin.app.restore" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/soft-delete$/, methods: { POST: "admin.app.delete" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployment-bindings$/, methods: { GET: "admin.deployment.bindings.read", POST: "admin.deployment.bindings.create" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployment-bindings\/[^/]+$/, methods: { PATCH: "admin.deployment.bindings.update" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployment-bindings\/[^/]+\/verify$/, methods: { POST: "admin.deployment.bindings.verify" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/releases$/, methods: { GET: "admin.deployment.releases.read" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/releases\/[^/]+\/deploy-staging$/, methods: { POST: "admin.deployment.release.deploy_staging" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/releases\/[^/]+\/approve-production$/, methods: { POST: "admin.deployment.release.approve_production" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployments$/, methods: { GET: "admin.deployment.deployments.read" } },
  { pattern: /^\/v1\/internal\/apps\/[^/]+\/releases$/, methods: { POST: "service.deployment.release_create" } },
  { pattern: /^\/v1\/internal\/apps\/[^/]+\/published-deployment$/, methods: { GET: "service.deployment.published.read" } },
  { pattern: /^\/v1\/internal\/deployments\/safety-sweep$/, methods: { POST: "service.deployment.safety_sweep" } },
  { pattern: /^\/v1\/internal\/deployments\/window-sweep$/, methods: { POST: "service.deployment.window_sweep" } },
  { pattern: /^\/v1\/internal\/deployment-provider\/webhook$/, methods: { POST: "service.deployment.webhook_ingest" } },
  { pattern: /^\/v1\/internal\/deployments\/retention-purge$/, methods: { POST: "service.deployment.retention_purge" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployments\/[^/]+\/schedule$/, methods: { POST: "deployment.schedule" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployments\/[^/]+\/reschedule$/, methods: { POST: "deployment.reschedule" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployments\/[^/]+\/cancel$/, methods: { POST: "deployment.cancel" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployments\/[^/]+\/promote$/, methods: { POST: "deployment.promote" } },
  // AR-002 session 2: this URL is now backed by the real rollback service
  // (src/lib/deployment-rollback/service.ts), not AU-001's
  // deployment-service.ts scaffold — deployment.rollback (AU-001's own
  // action, still defined in AUTHORIZATION_ACTIONS for
  // tests/au-001.acceptance.test.ts AC44) is intentionally no longer the
  // declaration for this path.
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployments\/[^/]+\/rollback$/, methods: { POST: "admin.deployment.rollback" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployment-windows$/, methods: { GET: "admin.deployment.windows.read", POST: "admin.deployment.windows.schedule" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployment-windows\/[^/]+$/, methods: { PATCH: "admin.deployment.windows.reschedule" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/deployment-windows\/[^/]+\/cancel$/, methods: { POST: "admin.deployment.windows.cancel" } },
  { pattern: /^\/v1\/internal\/analytics\/daily-contribution$/, methods: { POST: "service.analytics.contribute" } },
  { pattern: /^\/v1\/internal\/analytics\/daily-runs\/[^/]+$/, methods: { POST: "service.analytics.run" } },
  { pattern: /^\/v1\/internal\/authorization\/decision$/, methods: { POST: "service.authorization.decide" } },
  { pattern: /^\/v1\/internal\/entitlements\/apply-paid-cycle$/, methods: { POST: "service.entitlements.apply_cycle" } },
  { pattern: /^\/v1\/internal\/entitlements\/evaluate-access$/, methods: { POST: "service.entitlements.evaluate_access" } },
  { pattern: /^\/v1\/internal\/billing\/reconcile$/, methods: { POST: "service.billing.reconcile" } },
  { pattern: /^\/v1\/internal\/billing\/upcoming-renewal-reminder-sweep$/, methods: { POST: "service.billing.renewal_reminder" } },
  { pattern: /^\/v1\/internal\/billing\/grace-expiry-sweep$/, methods: { POST: "service.billing.grace_expiry" } },
  { pattern: /^\/v1\/internal\/app-launch\/exchange$/, methods: { POST: "app.launch.exchange" } },
  { pattern: /^\/v1\/internal\/app-session-grants\/[^/]+\/renew$/, methods: { POST: "app.grant.renew" } },
  { pattern: /^\/v1\/internal\/app-session-grants\/[^/]+\/status$/, methods: { GET: "app.grant.status" } },
  { pattern: /^\/v1\/internal\/learner-app-progress\/completions$/, methods: { GET: "app.progress.completions.read" } },
  { pattern: /^\/v1\/internal\/learner-app-progress\/current$/, methods: { GET: "app.progress.current.read", PUT: "app.progress.write" } },
  { pattern: /^\/v1\/internal\/learner-app-progress\/lessons\/[^/]+\/complete$/, methods: { POST: "app.lesson.complete" } },
  { pattern: /^\/v1\/internal\/learner-sessions\/[^/]+\/complete$/, methods: { POST: "app.session.complete" } },
  { pattern: /^\/v1\/internal\/learner-sessions\/[^/]+\/disconnect$/, methods: { POST: "app.session.disconnect" } },
  { pattern: /^\/v1\/internal\/learner-sessions\/[^/]+\/resume$/, methods: { POST: "app.session.resume" } },
  { pattern: /^\/v1\/internal\/learner-sessions\/[^/]+\/usable-launch$/, methods: { POST: "app.session.usable_launch" } },
  { pattern: /^\/v1\/internal\/learner-app-progress\/validate-integrity$/, methods: { POST: "app.progress.integrity.validate" } },
  { pattern: /^\/v1\/internal\/learner-app-progress\/reconcile-integrity$/, methods: { POST: "service.progress_integrity.reconcile" } },
  { pattern: /^\/v1\/admin\/progress-integrity-incidents\/[^/]+$/, methods: { GET: "admin.progress_integrity.incident.read" } },
  { pattern: /^\/v1\/admin\/progress-integrity-incidents\/[^/]+\/action$/, methods: { POST: "admin.progress_integrity.incident.action" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/progress-integrity-health$/, methods: { GET: "admin.progress_integrity.health.read" } },
  { pattern: /^\/v1\/internal\/learner-app-progress\/recover-current$/, methods: { POST: "app.progress.recover" } },
  { pattern: /^\/v1\/internal\/learner-app-progress\/reconcile-recovery$/, methods: { POST: "service.progress_recovery.reconcile" } },
  { pattern: /^\/v1\/admin\/apps\/[^/]+\/progress-recovery-incidents$/, methods: { GET: "admin.progress_recovery.incidents.read" } },
] as const;

export function resolveApiRouteAuthorization(method: string, pathname: string) {
  const route = API_ROUTE_AUTHORIZATION.find((candidate) => candidate.pattern.test(pathname));
  return route?.methods[method.toUpperCase()];
}
